### ISSUE TITLE
Long Short HRP

### ISSUE THREAD

**Issue by waudinio27** [TheRockXu/Hierarchical-Risk-Parity#1]
Hello Rocky!

Thanks a lot for your great work. What I like about it especially is that it does not need as many dependencies and that it keeps everything simple and easy to follow.

I have a question. Could you show the implementation of a  Hierarchical_Risk_Parity  Portfolio  for an only Short Portfolio with Forex Data as well in a jupyter notebook? A Long-Short Portfolio is not possible by default - but  maybe it is possible to make a Short only Portfolio? What you think?

I really would appreciate it a lot to have the possibility to try it out myself.

Thanks a lot in advance

Matthias

**Comment by TheRockXu** [comment]
Yeah, I haven't done so. But a rough idea is to flip the signs of the data and concat them as new. AAPL is the long, -AAPL means short.   Then run the optimization process.
